name: "build"
on: [pull_request]
env:
  TRIVY_VERSION: 0.49.0
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@1.5.4
        with:
          support-path: ${{ github.workspace }}/lib/bats-support
          assert-path: ${{ github.workspace }}/lib/bats-assert
          file-path: ${{ github.workspace }}/lib/bats-file


      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v${{ env.TRIVY_VERSION }}

      - name: Test
        run: bats --recursive --timing .
        env:
          BATS_LIB_PATH: ${{ github.workspace }}/lib
